- name: Setup EC2 server
  hosts: web
  become: true

  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Docker
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes